name: Terraform CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-west-1

jobs:
  terraform:
    name: Validate & plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Override region from repository variables
        if: vars.AWS_REGION != ''
        run: echo "AWS_REGION=${{ vars.AWS_REGION }}" >> "$GITHUB_ENV"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -out=tfplan.binary
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: aws-setup/tfplan.binary
          if-no-files-found: error
